# Generated by Django 5.1.15 on 2026-06-21 06:59

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models
from pgvector.django import VectorExtension


def create_hnsw_index(apps, schema_editor):
    """Create the pgvector HNSW index, but only on PostgreSQL.

    The HNSW index uses `USING hnsw (...) WITH (...)`, which non-Postgres backends
    (e.g. SQLite used for local checks) cannot parse. The index stays recorded in
    Django's migration state via SeparateDatabaseAndState, so model and DB remain
    consistent on Postgres.
    """
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        "CREATE INDEX IF NOT EXISTS embeddingchunk_hnsw "
        "ON exam_intelligence_embeddingchunk "
        "USING hnsw (embedding vector_cosine_ops) "
        "WITH (m = 16, ef_construction = 64)"
    )


def drop_hnsw_index(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute("DROP INDEX IF EXISTS embeddingchunk_hnsw")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Enable pgvector before any vector column/index. No-op on non-Postgres.
        # Requires privilege to CREATE EXTENSION (local superuser, or have an admin
        # run `CREATE EXTENSION vector;` once beforehand).
        VectorExtension(),
        migrations.CreateModel(
            name='BacSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name_fr', models.CharField(max_length=120)),
                ('name_ar', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=48)),
                ('name_fr', models.CharField(max_length=160)),
                ('name_ar', models.CharField(blank=True, max_length=160)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['subject', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumEra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('start_year', models.PositiveSmallIntegerField()),
                ('end_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('relevance_weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
            ],
            options={
                'ordering': ['-start_year'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name_fr', models.CharField(max_length=120)),
                ('name_ar', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('name_fr', models.CharField(max_length=200)),
                ('name_ar', models.CharField(blank=True, max_length=200)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='exam_intelligence.chapter')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='exam_intelligence.concept')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='era',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chapters', to='exam_intelligence.curriculumera'),
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('session', models.CharField(choices=[('principale', 'Session principale'), ('controle', 'Session de contrôle')], max_length=16)),
                ('era', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='exam_intelligence.curriculumera')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='exam_intelligence.bacsection')),
            ],
        ),
        migrations.CreateModel(
            name='ExamExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(blank=True, max_length=200)),
                ('intro_text', models.TextField(blank=True)),
                ('total_points', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('difficulty', models.CharField(blank=True, choices=[('easy', 'Facile'), ('medium', 'Moyen'), ('hard', 'Difficile')], max_length=8, null=True)),
                ('estimated_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('relevance_status', models.CharField(choices=[('relevant', 'Pertinent (programme actuel)'), ('partially', 'Partiellement pertinent'), ('outdated', 'Hors programme actuel'), ('unreviewed', 'Non revu')], default='unreviewed', max_length=12)),
                ('relevance_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('validated_by_teacher', models.BooleanField(default=False)),
                ('chapters', models.ManyToManyField(blank=True, related_name='exercises', to='exam_intelligence.chapter')),
                ('concepts', models.ManyToManyField(blank=True, related_name='exercises', to='exam_intelligence.concept')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='exam_intelligence.exam')),
            ],
            options={
                'ordering': ['exam', 'number'],
            },
        ),
        migrations.CreateModel(
            name='CommonMistake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_fr', models.CharField(max_length=300)),
                ('description_ar', models.CharField(blank=True, max_length=300)),
                ('why_it_happens', models.TextField(blank=True)),
                ('correct_approach', models.TextField(blank=True)),
                ('frequency', models.CharField(choices=[('rare', 'Rare'), ('occasional', 'Occasionnel'), ('common', 'Fréquent'), ('very_common', 'Très fréquent')], default='common', max_length=12)),
                ('concept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='common_mistakes', to='exam_intelligence.concept')),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='common_mistakes', to='exam_intelligence.examexercise')),
            ],
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16)),
                ('text', models.TextField()),
                ('points', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('concepts', models.ManyToManyField(blank=True, related_name='questions', to='exam_intelligence.concept')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exam_intelligence.examexercise')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subquestions', to='exam_intelligence.examquestion')),
            ],
            options={
                'ordering': ['exercise', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_official', models.BooleanField(default=False)),
                ('author_type', models.CharField(choices=[('official', 'Officielle'), ('teacher', 'Enseignant'), ('ai_draft', 'Brouillon IA')], default='official', max_length=16)),
                ('reliability', models.CharField(choices=[('high', 'Élevée'), ('medium', 'Moyenne'), ('low', 'Faible')], default='high', max_length=8)),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='exam_intelligence.examexercise')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='exam_intelligence.examquestion')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_type', models.CharField(choices=[('skill', 'Type de compétence'), ('method', 'Méthode requise'), ('difficulty', 'Difficulté'), ('language', 'Langue'), ('relevance', 'Pertinence'), ('frequency', 'Fréquence'), ('other', 'Autre')], max_length=16)),
                ('value', models.CharField(max_length=120)),
                ('source', models.CharField(choices=[('auto', 'Automatique'), ('reviewed', 'Validé')], default='auto', max_length=10)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='exam_intelligence.examexercise')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastery', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('correct', models.PositiveIntegerField(default=0)),
                ('last_practiced', models.DateTimeField(blank=True, null=True)),
                ('decay_applied_at', models.DateTimeField(blank=True, null=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_states', to='exam_intelligence.concept')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_states', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RubricItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('points', models.DecimalField(decimal_places=2, max_digits=4)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('correction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_items', to='exam_intelligence.correction')),
            ],
            options={
                'ordering': ['correction', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SourceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=512)),
                ('original_filename', models.CharField(max_length=512)),
                ('doc_type', models.CharField(choices=[('exam', 'Énoncé'), ('correction', 'Correction')], max_length=16)),
                ('is_scanned', models.BooleanField(default=False)),
                ('detected_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('detected_session', models.CharField(blank=True, choices=[('principale', 'Session principale'), ('controle', 'Session de contrôle')], max_length=16, null=True)),
                ('ocr_engine', models.CharField(blank=True, max_length=32)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('review_status', models.CharField(choices=[('pending', 'En attente de revue'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=16)),
                ('raw_text', models.TextField(blank=True)),
                ('cleaned_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('detected_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam_intelligence.bacsection')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL)),
                ('detected_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam_intelligence.subject')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='source_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='exam_intelligence.sourcedocument'),
        ),
        migrations.AddField(
            model_name='correction',
            name='source_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to='exam_intelligence.sourcedocument'),
        ),
        migrations.CreateModel(
            name='StudentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_type', models.CharField(choices=[('mcq', 'QCM'), ('text', 'Réponse rédigée'), ('image', 'Photo/PDF')], max_length=8)),
                ('raw_answer', models.TextField(blank=True)),
                ('estimated_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('mistakes', models.JSONField(blank=True, default=list)),
                ('feedback', models.JSONField(blank=True, default=dict)),
                ('is_diagnostic', models.BooleanField(default=False)),
                ('is_mock', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='exam_intelligence.examexercise')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='exam_intelligence.examquestion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MistakeNotebookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('common_mistake', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notebook_entries', to='exam_intelligence.commonmistake')),
                ('concept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notebook_entries', to='exam_intelligence.concept')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistake_notebook', to=settings.AUTH_USER_MODEL)),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notebook_entries', to='exam_intelligence.studentattempt')),
            ],
        ),
        migrations.CreateModel(
            name='SectionSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.DecimalField(decimal_places=2, max_digits=4)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_subjects', to='exam_intelligence.bacsection')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_sections', to='exam_intelligence.subject')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='exam_intelligence.subject'),
        ),
        migrations.CreateModel(
            name='EmbeddingChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('content_type', models.CharField(choices=[('lesson', 'Résumé de cours'), ('exercise', "Énoncé d'exercice"), ('question', 'Question'), ('correction', 'Correction'), ('rubric', 'Barème'), ('mistake', 'Erreur fréquente')], max_length=16)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('model_name', models.CharField(max_length=64)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('relevance_weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('relevance_status', models.CharField(choices=[('relevant', 'Pertinent (programme actuel)'), ('partially', 'Partiellement pertinent'), ('outdated', 'Hors programme actuel'), ('unreviewed', 'Non revu')], default='unreviewed', max_length=12)),
                ('source_object_type', models.CharField(blank=True, max_length=32)),
                ('source_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chunks', to='exam_intelligence.chapter')),
                ('era', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chunks', to='exam_intelligence.curriculumera')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='exam_intelligence.bacsection')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='exam_intelligence.subject')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='exam_intelligence.subject'),
        ),
        migrations.CreateModel(
            name='AIInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('explain_fr', 'Explication FR'), ('explain_ar', 'Explication AR'), ('explain_darja', 'Explication Darja'), ('hint_only', 'Indice'), ('full_correction', 'Correction complète'), ('bac_style_answer', 'Réponse type Bac'), ('identify_mistakes', "Repérage d'erreurs"), ('generate_similar', 'Exercice similaire'), ('revision_summary', 'Fiche de révision'), ('explain_points_lost', 'Points perdus')], max_length=24)),
                ('language', models.CharField(choices=[('fr', 'Français'), ('ar', 'العربية'), ('darja', 'Darija tunisienne')], default='fr', max_length=8)),
                ('query', models.TextField()),
                ('retrieved_chunk_ids', models.JSONField(blank=True, default=list)),
                ('response', models.TextField()),
                ('citations', models.JSONField(blank=True, default=list)),
                ('used_sources', models.BooleanField(default=False)),
                ('model_name', models.CharField(blank=True, max_length=64)),
                ('tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['mode', 'created_at'], name='exam_intell_mode_3cb958_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='concept',
            constraint=models.UniqueConstraint(fields=('chapter', 'code'), name='uniq_concept'),
        ),
        migrations.AddConstraint(
            model_name='examexercise',
            constraint=models.UniqueConstraint(fields=('exam', 'number'), name='uniq_exercise_in_exam'),
        ),
        migrations.AddConstraint(
            model_name='examquestion',
            constraint=models.UniqueConstraint(fields=('exercise', 'number'), name='uniq_question_in_exercise'),
        ),
        migrations.AddIndex(
            model_name='exercisetag',
            index=models.Index(fields=['tag_type', 'value'], name='exam_intell_tag_typ_689fdf_idx'),
        ),
        migrations.AddConstraint(
            model_name='exercisetag',
            constraint=models.UniqueConstraint(fields=('exercise', 'tag_type', 'value'), name='uniq_exercise_tag'),
        ),
        migrations.AddConstraint(
            model_name='knowledgestate',
            constraint=models.UniqueConstraint(fields=('student', 'concept'), name='uniq_student_concept'),
        ),
        migrations.AddConstraint(
            model_name='correction',
            constraint=models.CheckConstraint(condition=models.Q(('question__isnull', False), ('exercise__isnull', False), _connector='OR'), name='correction_targets_question_or_exercise'),
        ),
        migrations.AddIndex(
            model_name='studentattempt',
            index=models.Index(fields=['student', 'created_at'], name='exam_intell_student_d66b1f_idx'),
        ),
        migrations.AddIndex(
            model_name='mistakenotebookentry',
            index=models.Index(fields=['student', 'resolved'], name='exam_intell_student_404d78_idx'),
        ),
        migrations.AddIndex(
            model_name='sourcedocument',
            index=models.Index(fields=['review_status'], name='exam_intell_review__25860c_idx'),
        ),
        migrations.AddIndex(
            model_name='sourcedocument',
            index=models.Index(fields=['detected_year', 'detected_subject'], name='exam_intell_detecte_9e2532_idx'),
        ),
        migrations.AddConstraint(
            model_name='sectionsubject',
            constraint=models.UniqueConstraint(fields=('section', 'subject'), name='uniq_section_subject'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['subject', 'year'], name='exam_intell_subject_205bba_idx'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.UniqueConstraint(fields=('section', 'subject', 'year', 'session'), name='uniq_exam_slot'),
        ),
        migrations.AddIndex(
            model_name='embeddingchunk',
            index=models.Index(fields=['content_type'], name='exam_intell_content_b892f7_idx'),
        ),
        migrations.AddIndex(
            model_name='embeddingchunk',
            index=models.Index(fields=['subject', 'section'], name='exam_intell_subject_7db0a9_idx'),
        ),
        migrations.AddIndex(
            model_name='embeddingchunk',
            index=models.Index(fields=['year'], name='exam_intell_year_e53b57_idx'),
        ),
        migrations.AddIndex(
            model_name='embeddingchunk',
            index=models.Index(fields=['relevance_status'], name='exam_intell_relevan_4f14ec_idx'),
        ),
        # HNSW index: kept in model state, but created in the DB only on Postgres.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name='embeddingchunk',
                    index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='embeddingchunk_hnsw', opclasses=['vector_cosine_ops']),
                ),
            ],
            database_operations=[
                migrations.RunPython(create_hnsw_index, drop_hnsw_index),
            ],
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('subject', 'era', 'code'), name='uniq_chapter'),
        ),
    ]
