# Generated by Django 5.1.15 on 2026-06-21 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_intelligence', '0003_aiinteraction_tutor_audit'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.CharField(max_length=32)),
                ('model_name', models.CharField(blank=True, max_length=64)),
                ('cases_path', models.CharField(blank=True, max_length=512)),
                ('total_cases', models.PositiveIntegerField(default=0)),
                ('passed_cases', models.PositiveIntegerField(default=0)),
                ('failed_cases', models.PositiveIntegerField(default=0)),
                ('score', models.FloatField(default=0.0)),
                ('fail_under', models.FloatField(default=0.0)),
                ('passed_threshold', models.BooleanField(default=False)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('git_commit_sha', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='exam_intell_created_dc0b63_idx'), models.Index(fields=['provider', 'model_name'], name='exam_intell_provide_83ae3e_idx')],
            },
        ),
        migrations.CreateModel(
            name='EvaluationCaseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=128)),
                ('query', models.TextField(blank=True)),
                ('expected_refused', models.BooleanField(default=False)),
                ('actual_refused', models.BooleanField(blank=True, null=True)),
                ('passed', models.BooleanField(default=False)),
                ('score', models.FloatField(default=0.0)),
                ('failures', models.JSONField(blank=True, default=list)),
                ('required_terms_found', models.JSONField(blank=True, default=list)),
                ('required_terms_missing', models.JSONField(blank=True, default=list)),
                ('forbidden_terms_found', models.JSONField(blank=True, default=list)),
                ('citation_count', models.PositiveIntegerField(default=0)),
                ('citation_chapters', models.JSONField(blank=True, default=list)),
                ('answer_preview', models.TextField(blank=True)),
                ('diagnostics_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eval_case_results', to='exam_intelligence.aiinteraction')),
                ('evaluation_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_results', to='exam_intelligence.evaluationrun')),
            ],
            options={
                'ordering': ['evaluation_run', 'case_id'],
                'indexes': [models.Index(fields=['evaluation_run', 'case_id'], name='exam_intell_evaluat_b002ff_idx'), models.Index(fields=['passed'], name='exam_intell_passed_a7989e_idx')],
            },
        ),
    ]
